### ISSUE TITLE
EPIC: Artists

### ISSUE THREAD

**Issue by Dym077** [Dym077/django-blog#20]
As a **developer** I can **create an artists page** so that **users and artists can interact**

***Acceptance Criteria

- [ ] Artists can register a dedicated profile
- [ ] Artists can upload images in high resolution
- [ ] Artists can interact with eachother and other users

**Comment by Dym077** [comment]
I'm considering implenting this as a future feature instead, as this get far too complex for this project at the current interation.
