### ISSUE TITLE
EPIC: Authentication

### ISSUE THREAD

**Issue by Dym077** [Dym077/django-blog#49]
As a **user** I can **create a unique username and password** so that **I can log onto the site**

***Acceptance Criteria

- [x] User can create a username
- [x] User can create a password
- [x] User can log in with these credentials
